#!/bin/sh

python -q ./bot.py > ./headline & curl -silent https://corona-stats.online/gb > ./stats &&
	printf "\n\n\n"
	grep "UK\|World" ./stats | sed "s/\s*//g ; s/║//g ; s/│/;/g" |
		awk -F';' '{print $2 "   " $8" 😷" "   " $5" 💀" "   "$7" 👌" }'

	printf "\nFetching CIDRAP (Center for Infectious Disease Research and Policy) news report...\n\n"
wait && cat ./headline
printf "\n"
